# Generated by Django 6.0.7 on 2026-07-31 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Kalkan Nilüfer Butik', max_length=100)),
                ('tagline', models.CharField(default='Modern boutique experience', max_length=200)),
                ('email', models.EmailField(default='hello@butikmail.local', max_length=254)),
                ('about_text', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
    ]
