# Generated by Django 6.0.7 on 2026-08-21 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Kalkan Nilüfer Butik', max_length=100)),
                ('tagline', models.CharField(default='Doğallığın ve şıklığın buluştuğu adres...', max_length=200)),
                ('tagline_en', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(default='hello@butikmail.local', max_length=254)),
                ('about_text', models.TextField(blank=True)),
                ('about_text_en', models.TextField(blank=True)),
                ('location', models.CharField(default='Kalkan, Antalya', max_length=200)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('new_arrivals_image', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('bottom_image', models.ImageField(blank=True, null=True, upload_to='site/')),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
    ]
